# Shows a "Sponsor" button on the GitHub repo.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://buymeacoffee.com/scpg.dev"]
