import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# ---------------------------------------------------------------------------
# Fixture pattern-file discovery helpers (shared across integration tests)
# ---------------------------------------------------------------------------
# Priority for xlsx:  pattern-manual.xlsx  >  pattern-from-draft.xlsx  >  pattern.xlsx
# Priority for csv:   pattern-manual.csv   >  pattern-from-draft.csv
# The legacy 'pattern.xlsx' fallback keeps tests green during any in-progress
# rename.  pattern-manual.* files are user-curated and must never be written
# or regenerated by tooling — treat them as read-only.

_PATTERN_XLSX_NAMES = ('pattern-manual.xlsx', 'pattern-from-draft.xlsx', 'pattern.xlsx')
_PATTERN_CSV_NAMES  = ('pattern-manual.csv',  'pattern-from-draft.csv')


def find_pattern_xlsx(folder: str) -> str | None:
    """Return the highest-priority pattern xlsx in a fixture folder, or None."""
    for name in _PATTERN_XLSX_NAMES:
        p = os.path.join(folder, name)
        if os.path.exists(p):
            return p
    return None


def find_pattern_csv(folder: str) -> str | None:
    """Return a real authored pattern csv in a fixture folder, or None.

    Only returns a path when an actual committed CSV file exists — not for
    synthetically-converted temp files.  Used for the Level-2 real-file test.
    """
    for name in _PATTERN_CSV_NAMES:
        p = os.path.join(folder, name)
        if os.path.exists(p):
            return p
    return None
