import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# ---------------------------------------------------------------------------
# Fixture file discovery helpers (shared across integration tests)
# ---------------------------------------------------------------------------
# Naming convention:
#
#   {name}_data.xlsx
#   {name}_data-cdr.xlsx                 — security CDR (macros/VBA stripped)
#   {name}_pattern-manual.xlsx           — hand-crafted, read-only
#   {name}_pattern-from-claude.xlsx/.csv — generated by Claude API backend
#   {name}_pattern-from-local.xlsx/.csv  — generated by local LLM (llama-cpp)
#   {name}_pattern-from-github.xlsx/.csv — generated by GitHub Models backend
#   {name}_pattern-from-gemini.xlsx/.csv — generated by Gemini backend
#   {name}_pattern-from-draft.xlsx/.csv  — legacy baseline (programmatic for 01-14,
#                                          original grepxcel draft for 15-22)
#   {name}_snapshot-from-{backend}.json  — stored extraction result for regression tests
#   {name}_snapshot-manual.json          — stored extraction result using manual pattern
#
# Priority for xlsx:  manual > from-claude > from-local > from-github > from-gemini
#                     > from-draft > pattern (bare legacy)
# Priority for csv:   manual > from-claude > from-local > from-github > from-gemini
#                     > from-draft
#
# pattern-manual.* files are user-curated — treat as read-only.

# Ordered by priority (highest first).
_BACKENDS = ('claude', 'local', 'github', 'gemini', 'draft')

_PATTERN_XLSX_SUFFIXES = (
    'pattern-manual.xlsx',
    'pattern-from-claude.xlsx',
    'pattern-from-local.xlsx',
    'pattern-from-github.xlsx',
    'pattern-from-gemini.xlsx',
    'pattern-from-draft.xlsx',   # legacy / programmatic (01-14) or original draft (15-22)
    'pattern.xlsx',              # bare legacy fallback
)
_PATTERN_CSV_SUFFIXES = (
    'pattern-manual.csv',
    'pattern-from-claude.csv',
    'pattern-from-local.csv',
    'pattern-from-github.csv',
    'pattern-from-gemini.csv',
    'pattern-from-draft.csv',
)

# Keep the old constants as aliases for any code that still imports them.
_PATTERN_XLSX_NAMES = _PATTERN_XLSX_SUFFIXES
_PATTERN_CSV_NAMES  = _PATTERN_CSV_SUFFIXES


def find_data_file(folder: str) -> str:
    """Return the data xlsx path for a fixture folder.

    Prefers the prefixed name ({name}_data.xlsx).  Falls back to the legacy
    bare name (data.xlsx) so tests work during migration.
    """
    name = os.path.basename(folder)
    new  = os.path.join(folder, f'{name}_data.xlsx')
    if os.path.exists(new):
        return new
    return os.path.join(folder, 'data.xlsx')


def find_pattern_xlsx(folder: str) -> str | None:
    """Return the highest-priority pattern xlsx in a fixture folder, or None.

    For each priority level tries the prefixed name first, then the bare
    legacy name.
    """
    name = os.path.basename(folder)
    for suffix in _PATTERN_XLSX_SUFFIXES:
        for candidate in (f'{name}_{suffix}', suffix):
            p = os.path.join(folder, candidate)
            if os.path.exists(p):
                return p
    return None


def find_pattern_csv(folder: str) -> str | None:
    """Return a real authored pattern csv in a fixture folder, or None.

    Only returns a path when an actual committed CSV file exists — not for
    synthetically-converted temp files.  Used for the Level-2 real-file test.
    """
    name = os.path.basename(folder)
    for suffix in _PATTERN_CSV_SUFFIXES:
        for candidate in (f'{name}_{suffix}', suffix):
            p = os.path.join(folder, candidate)
            if os.path.exists(p):
                return p
    return None


def find_pattern_for_backend(folder: str, backend: str) -> str | None:
    """Return the pattern xlsx for a specific backend, or None.

    backend is one of _BACKENDS ('claude', 'local', 'github', 'gemini', 'draft')
    or 'manual'.
    """
    name = os.path.basename(folder)
    if backend == 'manual':
        suffix = 'pattern-manual.xlsx'
    else:
        suffix = f'pattern-from-{backend}.xlsx'
    p = os.path.join(folder, f'{name}_{suffix}')
    return p if os.path.exists(p) else None


def find_snapshot(folder: str, source: str) -> str | None:
    """Return the snapshot JSON path for a given source, or None.

    source is a backend name ('claude', 'local', …, 'draft') or 'manual'.
    """
    name = os.path.basename(folder)
    filename = (f'{name}_snapshot-manual.json' if source == 'manual'
                else f'{name}_snapshot-from-{source}.json')
    p = os.path.join(folder, filename)
    return p if os.path.exists(p) else None


def find_extraction_config(folder: str) -> dict:
    """Return optional extraction parameters stored in {name}_extraction_config.json.

    Used by generate_snapshots.py and test_snapshots.py to pass fixture-specific
    kwargs (e.g. sheet='Details') to Engine().process().  Returns {} if no config
    file exists.
    """
    import json as _json
    name = os.path.basename(folder)
    p = os.path.join(folder, f'{name}_extraction_config.json')
    if not os.path.exists(p):
        return {}
    with open(p, encoding='utf-8') as fh:
        return _json.load(fh)


def list_snapshots(folder: str) -> list[tuple[str, str]]:
    """Return (source, path) for every snapshot JSON present in the fixture folder.

    Sources are checked in priority order: backends then manual.
    """
    result = []
    for source in (*_BACKENDS, 'manual'):
        p = find_snapshot(folder, source)
        if p:
            result.append((source, p))
    return result
