"""
DocsGenerator — writes a self-documenting pattern-reference.xlsx.

The output file is both human-readable documentation and a valid grepxcel
pattern that the engine can parse.  Every keyword is shown in context with
colour coding:

  doc:    — yellow   (inline comment, ignored by engine)
  lbl:    — blue     (anchor label, never in output JSON)
  var:    — green    (variable, extracted to output JSON)
  config: — orange   (global settings)
  cell:   — lavender (cell extraction instruction)
  table:  — lavender (table extraction instruction)
  START:/END: — grey (section markers)
  HEADER/DATA/FOOTER — light lavender (table template rows)
"""

import datetime
import os

import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment


def _pin_core_timestamps(path: str, ts: datetime.datetime) -> None:
    """Make the workbook byte-reproducible. openpyxl stamps both core.xml's
    <modified> AND every zip member's mod-time with now() on save, so we patch
    core.xml's created/modified and rewrite every member with a fixed mod-time."""
    import re
    import zipfile

    ts_iso = ts.strftime('%Y-%m-%dT%H:%M:%SZ')
    fixed_date = (ts.year, ts.month, ts.day, ts.hour, ts.minute, ts.second)

    with zipfile.ZipFile(path) as zin:
        infos = zin.infolist()
        data = {i.filename: zin.read(i.filename) for i in infos}
    core = data.get('docProps/core.xml')
    if core is not None:
        text = core.decode('utf-8')
        for tag in ('created', 'modified'):
            text = re.sub(rf'(<dcterms:{tag}[^>]*>)[^<]*(</dcterms:{tag}>)',
                          rf'\g<1>{ts_iso}\g<2>', text)
        data['docProps/core.xml'] = text.encode('utf-8')

    tmp = path + '.tmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as zout:
        for info in infos:                     # preserve order; fix the mod-time
            zi = zipfile.ZipInfo(info.filename, date_time=fixed_date)
            zi.compress_type = info.compress_type
            zi.external_attr = info.external_attr
            zi.internal_attr = info.internal_attr
            zi.create_system = info.create_system
            zout.writestr(zi, data[info.filename])
    os.replace(tmp, path)


# Row colours (ARGB hex, no leading '#')
_FILL = {
    'doc':     PatternFill('solid', fgColor='FFFFD0'),  # yellow
    'lbl':     PatternFill('solid', fgColor='D0E8FF'),  # blue
    'var':     PatternFill('solid', fgColor='D0FFD0'),  # green
    'config':  PatternFill('solid', fgColor='FFE8D0'),  # orange
    'cell':    PatternFill('solid', fgColor='F0E0FF'),  # lavender
    'table':   PatternFill('solid', fgColor='F0E0FF'),  # lavender
    'marker':  PatternFill('solid', fgColor='E0E0E0'),  # grey  (START/END)
    'tmpl':    PatternFill('solid', fgColor='F8F0FF'),  # light lavender
}

_BOLD = Font(bold=True)


def _row(ws, row_num: int, cells: list, fill_key: str) -> None:
    fill = _FILL.get(fill_key)
    for col, val in enumerate(cells, start=1):
        c = ws.cell(row=row_num, column=col, value=val)
        if fill:
            c.fill = fill


class DocsGenerator:
    def write(self, output_path: str) -> None:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = 'pattern-reference'

        # Column widths (A, B, C, D, E)
        ws.column_dimensions['A'].width = 14
        ws.column_dimensions['B'].width = 20
        ws.column_dimensions['C'].width = 12
        ws.column_dimensions['D'].width = 28
        ws.column_dimensions['E'].width = 50

        r = 1

        def row(cells, fill_key=''):
            nonlocal r
            _row(ws, r, cells, fill_key)
            r += 1

        def blank():
            nonlocal r
            r += 1

        # ── How-to-regenerate header (for the Excel user) ─────────────────────
        row(['doc:', 'AUTO-GENERATED — do not edit this file directly.'], 'doc')
        row(['doc:', 'To regenerate it yourself, install grepxcel and run:'], 'doc')
        row(['doc:', '    grepxcel docs'], 'doc')
        row(['doc:', '    grepxcel docs -o /your/path/pattern-reference.xlsx'], 'doc')
        row(['doc:', 'A current copy is also available in the project repository under docs/.'], 'doc')
        blank()

        # ── Title ──────────────────────────────────────────────────────────────
        ws.cell(r, 1, 'grepxcel pattern reference').font = _BOLD
        ws.cell(r, 5, 'Column colour key:')
        ws.cell(r + 1, 5, 'doc:  — yellow  (comment, ignored)')
        ws.cell(r + 2, 5, 'lbl:  — blue    (anchor label, never in output)')
        ws.cell(r + 3, 5, 'var:  — green   (extracted variable)')
        ws.cell(r + 4, 5, 'config: — orange  (global setting)')
        ws.cell(r + 5, 5, 'cell:/table: — lavender  (instructions)')
        r += 2
        blank()

        # ── CONFIG section ─────────────────────────────────────────────────────
        row(['doc:', '', '', '', 'Config rows set global options. Must appear before lbl:/var: rows.'], 'doc')
        row(['config:', 'read.direction', 'LR', '', 'LR = left-to-right scan (default). TD = top-to-bottom.'], 'config')
        row(['config:', 'currency.sign', '€', '', 'Symbol used when parsing currency values.'], 'config')
        row(['config:', 'ignore.case', 'no', '', 'yes = match all regexes case-insensitively. Default no.'], 'config')
        blank()

        # ── LBL section ────────────────────────────────────────────────────────
        row(['doc:', '', '', '', 'lbl: defines an anchor label. Matched for position only — NEVER written to output JSON.'], 'doc')
        row(['doc:', '', '', '', 'Use lbl: for literal text like "Invoice No:" or table column headers like "Product".'], 'doc')
        row(['lbl:', 'po_label',     'string',   'PO Number:',  'Matches the literal text "PO Number:" in the sheet.'], 'lbl')
        row(['lbl:', 'date_label',   'string',   'Date:',       'Matches "Date:".'], 'lbl')
        row(['lbl:', 'vendor_label', 'string',   'Vendor:',     'Matches "Vendor:".'], 'lbl')
        row(['lbl:', 'col_item',     'string',   'Item',        'Table column header anchor.'], 'lbl')
        row(['lbl:', 'col_qty',      'string',   'Qty',         'Table column header anchor.'], 'lbl')
        row(['lbl:', 'col_price',    'string',   'Unit Price',  'Table column header anchor.'], 'lbl')
        row(['lbl:', 'col_total',    'string',   'Total',       'Table column header anchor.'], 'lbl')
        blank()

        # ── VAR section ────────────────────────────────────────────────────────
        row(['doc:', '', '', '', 'var: defines a data field. Extracted and written to output JSON.'], 'doc')
        row(['doc:', '', '', '', 'Dot notation creates nested JSON: po.number → {"po": {"number": ...}}'], 'doc')
        row(['doc:', '', '', '', 'All var: fields in one table DATA row must share the same group prefix.'], 'doc')
        row(['doc:', '', '', '', 'Types: string text integer number/float/decimal currency percentage boolean time duration date datetime'], 'doc')
        row(['doc:', '', '', '', 'Regex: Python re.fullmatch pattern. Leave blank (or .*) to accept any value of the declared type.'], 'doc')
        row(['doc:', '', '', '', 'Comments: a doc:/info: row is a whole-line comment. On config/var/lbl/cell/START rows,'], 'doc')
        row(['doc:', '', '', '', 'a cell starting with # AFTER the real columns is a trailing comment to end of row'], 'doc')
        row(['doc:', '', '', '', '(var:/lbl: → col E+, cell: → col C+, config: → col D+). NOT in table: rows (# is literal there).'], 'doc')
        row(['var:', 'po.number',    'string',   r'PO-[0-9]{4}',    'Matches e.g. "PO-2026". Output key: {"po": {"number": ...}}'], 'var')
        row(['var:', 'po.date',      'date',     '',                 'Any date value. Regex left empty → defaults to .*'], 'var')
        row(['var:', 'vendor.name',  'string',   '.+',              'Any non-empty string.'], 'var')
        row(['var:', 'line.item',    'string',   '.+',              'Table DATA field. Group prefix "line" → {"line": [...]}'], 'var')
        row(['var:', 'line.qty',     'integer',  r'[1-9][0-9]*',    'Positive integer.'], 'var')
        row(['var:', 'line.price',   'currency', '.*',              'Any currency value.'], 'var')
        row(['var:', 'line.total',   'currency', '.*',              'Any currency value.'], 'var')
        row(['var:', 'footer.label', 'string',   'Grand Total',     'FOOTER field — matches the literal "Grand Total".'], 'var')
        row(['var:', 'footer.value', 'currency', '.*',              'FOOTER value field.'], 'var')
        blank()

        # ── START section ──────────────────────────────────────────────────────
        row(['doc:', '', '', '', 'Everything between START: and END: defines the extraction order.'], 'doc')
        row(['doc:', '', '', '', 'cell:next  reads the next non-empty cell (alias: cell:1). Scans in read.direction order.'], 'doc')
        row(['doc:', '', '', '', 'cell:B5    jumps directly to cell B5 (absolute A1-notation reference).'], 'doc')
        row(['doc:', '', '', '', 'seek:G5    repositions the cursor to G5 WITHOUT reading it. Next cell:next starts from there.'], 'doc')
        row(['doc:', '', '', '', 'dir:LR     switches scan direction to left-to-right from here on (dir:TD = top-down).'], 'doc')
        row(['doc:', '', '', '', 'table:*    finds all instances of a repeating table block.'], 'doc')
        row(['START:'], 'marker')

        # cell instructions — showing both cell:next and cell:A1 styles
        row(['cell:A1', 'po_label',     '', '', 'Jump to A1 and read "PO Number:" anchor (lbl: field — not in output).'], 'cell')
        row(['cell:next', 'po.number',  '', '', 'Read next non-empty cell after A1 → the PO number.'], 'cell')
        row(['cell:C1', 'date_label',   '', '', 'Jump to C1 and read "Date:" anchor.'], 'cell')
        row(['cell:next', 'po.date',    '', '', 'Read next non-empty cell after C1 → the PO date.'], 'cell')
        row(['cell:next', 'vendor_label', '', '', 'Read next non-empty cell → "Vendor:" anchor.'], 'cell')
        row(['cell:next', 'vendor.name',  '', '', 'Extract the vendor name.'], 'cell')
        row(['doc:', '', '', '', 'Use IGNORE to skip a non-empty cell without defining a field for it.'], 'doc')
        row(['cell:next', 'IGNORE',     '', '', 'Skip one non-empty cell without capturing it.'], 'cell')
        blank()

        # table instruction + template rows
        row(['doc:', '', '', '', 'table:* matches 0-or-more mini-table instances in greedy order.'], 'doc')
        row(['doc:', '', '', '', 'Use table:1 when exactly one instance is expected.'], 'doc')
        row(['table:*'], 'table')
        row([None, 'HEADER:1', 'col_item', 'col_qty', 'col_price', 'col_total'], 'tmpl')
        row([None, 'DATA:*',   'line.item', 'line.qty', 'line.price', 'line.total'], 'tmpl')
        row([None, 'FOOTER:1', 'footer.label', 'IGNORE', 'IGNORE', 'footer.value'], 'tmpl')
        row(['doc:', '', '', '', 'HEADER/FOOTER are strict: wrong or missing value = no match.'], 'doc')
        row(['doc:', '', '', '', 'DATA rows are lenient: wrong value emits a warning but extraction continues.'], 'doc')
        row(['doc:', '', '', '', 'EMPTY column keyword: cell must be blank. IGNORE: consume without matching.'], 'doc')
        row(['doc:', '', '', '', '── BOUNDED DATA + SKIP_IF (fixed-slot templates) ───────────────────────'], 'doc')
        row(['doc:', '', '', '', 'Use DATA:{n,m} when the template pre-allocates a fixed number of rows.'], 'doc')
        row(['doc:', '', '', '', 'n = min total physical rows expected, m = max total rows to scan.'], 'doc')
        row(['doc:', '', '', '', 'SKIP_IF: rows matching the condition are silently excluded from output'], 'doc')
        row(['doc:', '', '', '', 'but still count toward the {n,m} bounds.'], 'doc')
        row(['doc:', '', '', '', 'SKIP_IF is valid with DATA:{n,m} (rows count toward bounds) and DATA:* (rows filtered, scan continues).'], 'doc')
        row(['table:1'], 'table')
        row([None, 'HEADER:1', 'col_item', 'col_qty'], 'tmpl')
        row([None, 'SKIP_IF',  'EMPTY',    'IGNORE'], 'tmpl')
        row([None, 'DATA:{0,15}', 'line.item', 'line.qty'], 'tmpl')
        row([None, 'FOOTER:1', 'lbl_total', 'inv.total'], 'tmpl')
        blank()

        row(['END:'], 'marker')
        blank()

        # ── Quick reference table ──────────────────────────────────────────────
        row(['doc:', '', '', '', '── QUICK REFERENCE ──────────────────────────────────────────────'], 'doc')
        ref = [
            ('doc:',     'doc: | free text',           'Inline comment. Ignored by engine.'),
            ('config:',  'config: | key | value',      'Global setting. Keys: read.direction, currency.sign, empty.aliases, ignore.case'),
            ('lbl:',     'lbl: | name | type | regex', 'Anchor label. Matched but never in output.'),
            ('var:',     'var: | name | type | regex', 'Extracted variable. Use dot notation for nesting.'),
            ('cell:next','cell:next | FieldName',      'Read next non-empty cell (alias: cell:1).'),
            ('cell:next','cell:next | IGNORE',         'Skip next non-empty cell without capturing.'),
            ('cell:next','cell:B5 | FieldName',        'Jump directly to B5 (absolute reference). Ordering must be forward.'),
            ('seek:',    'seek:G5',                    'Reposition cursor to G5 without reading it. Resets abs-ref ordering constraint.'),
            ('table:*',  'table:*  (or table:1)',      'Begin a repeating table block.'),
            ('HEADER:N', ' | HEADER:1 | F1 | F2',     'Strict header row template (col A must be blank).'),
            ('DATA:*',      ' | DATA:* | F1 | F2',           'Data row template (greedy, lenient validation).'),
            ('DATA:{n,m}',  ' | DATA:{0,15} | F1 | F2',      'Bounded data: scan at most m physical rows, warn if < n.'),
            ('SKIP_IF',     ' | SKIP_IF | EMPTY | IGNORE',    'Skip row if non-IGNORE columns match. Valid with DATA:{n,m} and DATA:*.'),
            ('FOOTER:N',    ' | FOOTER:1 | F1 | F2',          'Strict footer row template.'),
            ('SPLITTER',    ' | SPLITTER:1',                   'All columns must be blank (separator row).'),
        ]
        for keyword, syntax, description in ref:
            fill_key = keyword.rstrip(':*1').lower()
            if fill_key.startswith('header') or fill_key.startswith('data') or fill_key.startswith('footer') or fill_key.startswith('splitter'):
                fill_key = 'tmpl'
            row([keyword, syntax, '', description], fill_key)

        # Deterministic output so regenerating yields identical bytes (the
        # docs-reference CI check byte-compares). openpyxl forces <modified> to
        # now() at save time (writer/excel.py), so we pin the timestamps in
        # core.xml *after* saving. Honors SOURCE_DATE_EPOCH.
        epoch = os.environ.get('SOURCE_DATE_EPOCH')
        if epoch:
            ts = datetime.datetime.fromtimestamp(int(epoch), datetime.timezone.utc)
        else:
            ts = datetime.datetime(2020, 1, 1, tzinfo=datetime.timezone.utc)
        wb.save(output_path)
        _pin_core_timestamps(output_path, ts)
