#!/usr/bin/env python3
"""
Master fixture regeneration script.

Regenerates all fixture files that can be generated automatically, while
preserving files that are hand-crafted or produced by external tools.

PROTECTED (never touched):
  *_data.xlsx              — source truth (real-world or programmatically authored)
  *_data-cdr.xlsx          — OPSWAT MetaDefender CDR output (external tool)
  *-manual.xlsx            — hand-crafted patterns
  *_snapshot-manual.json   — snapshots of manual patterns (regenerated only with --paid)
  *_extraction_config.json — hand-authored sheet config (e.g. {"sheet": "Details"})
  *_pattern-from-draft.* for fixtures 15-22 — hand-authored reference baselines;
                                               no automated generation script exists

FREE TIER (always regenerated unless --skip-free):
  *_pattern-from-draft.* (fixtures 01-14)  — via scripts/generate_fixtures.py;
                                              *_data.xlsx is never overwritten
  *_snapshot-from-*.json                    — via scripts/generate_snapshots.py
                                              (pure extraction, no LLM calls)

PAID TIER (only with --paid; skipped by default to avoid unintended API spend):
  *_pattern-from-claude.*  — Claude API (paid tokens per call)
  *_pattern-from-local.*   — local LLM (slow; compute cost)
  Staleness check: a paid file is only regenerated when its source *_data.xlsx
  is newer than the existing pattern file.  Force with --force-paid.

  Exception — synthetic-data fixtures (01-14): their *_data.xlsx is generated by
  generate_fixtures.py which always rewrites the file (openpyxl ZIP timestamps),
  so the mtime is not a reliable signal.  These are skipped by --paid and only
  regenerated when --force-paid is passed explicitly.

Usage
-----
  # Regenerate free tier for all fixtures (draft patterns 01-14 + all snapshots)
  python3 scripts/regenerate_all_fixtures.py

  # Also regenerate paid patterns where source data is stale
  python3 scripts/regenerate_all_fixtures.py --paid

  # Regenerate paid patterns even if data is not newer (force refresh)
  python3 scripts/regenerate_all_fixtures.py --paid --force-paid

  # Only snapshots (skip draft pattern regeneration)
  python3 scripts/regenerate_all_fixtures.py --skip-free

  # Dry run: show what would be regenerated without doing it
  python3 scripts/regenerate_all_fixtures.py --dry-run
  python3 scripts/regenerate_all_fixtures.py --paid --dry-run
"""

import os
import sys
import argparse
import subprocess

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _bootstrap import ensure_venv; ensure_venv()

ROOT         = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
FIXTURES_DIR = os.path.join(ROOT, 'tests', 'fixtures')
SCRIPTS_DIR  = os.path.join(ROOT, 'scripts')

# Fixtures whose *_pattern-from-draft.* files are hand-authored baselines.
# There is no automated generation script for these; they are treated as
# protected (like *-manual.*) and never regenerated by this script.
_DRAFT_HAND_AUTHORED = {
    '15_annual_budget', '16_bundesliga', '17_excel_template_invoice',
    '18_billing_statement', '19_blood_pressure_tracker', '20_sales_report',
    '21_monthly_budget', '22_weekly_timesheet',
}

# Fixtures 01-14 have *_data.xlsx files generated by generate_fixtures.py.
# Their data content is defined in code, not sourced externally.  Running
# generate_fixtures.py updates the file timestamp even when the content is
# unchanged (openpyxl always writes a fresh ZIP), so timestamp-based staleness
# checks against these data files would falsely flag the claude patterns as
# stale on every free-tier run.
#
# Rule: for these fixtures, only regenerate paid patterns when --force-paid is
# passed; --paid alone skips them (they are "always current").
_SYNTHETIC_DATA_FIXTURES = {
    '01_simple_invoice', '02_product_catalog', '03_purchase_order',
    '04_bank_statement', '05_expense_report', '06_merged_cells',
    '07_timesheet', '08_price_list', '09_sales_by_region', '10_delivery_note',
    '11_loan_schedule', '12_multi_sheet', '13_hr_attendance', '14_named_tables',
}

# Local-model fixtures that produced valid patterns in the last run.
# Only these are regenerated when --paid is active for the local backend.
_LOCAL_BACKEND_FIXTURES = [
    '03_purchase_order',
    '08_price_list',
    '16_bundesliga',
    '21_monthly_budget',
]

VENV_PYTHON = os.path.join(ROOT, '.venv', 'bin', 'python3')


def _run(cmd: list[str], dry_run: bool, description: str) -> bool:
    """Run a command (or print it in dry-run mode). Returns True on success."""
    print(f'\n  → {description}', flush=True)
    if dry_run:
        print(f'    [DRY RUN] would run: {" ".join(cmd)}', flush=True)
        return True
    sys.stdout.flush()
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        print(f'    ✗ FAILED (exit {result.returncode})', file=sys.stderr, flush=True)
        return False
    return True


def _data_mtime(fixture_folder: str) -> float:
    """Return mtime of the fixture's source data file, or 0 if not found."""
    name = os.path.basename(fixture_folder)
    data = os.path.join(fixture_folder, f'{name}_data.xlsx')
    return os.path.getmtime(data) if os.path.exists(data) else 0.0


def _is_stale(fixture_folder: str, pattern_path: str) -> bool:
    """Return True if source data.xlsx is newer than the pattern file (or pattern missing)."""
    if not os.path.exists(pattern_path):
        return True
    return _data_mtime(fixture_folder) > os.path.getmtime(pattern_path)


def _all_fixtures() -> list[str]:
    return sorted(
        n for n in os.listdir(FIXTURES_DIR)
        if os.path.isdir(os.path.join(FIXTURES_DIR, n))
    )


def step_free_draft(dry_run: bool) -> bool:
    """Regenerate pattern-from-draft.* and data.xlsx for fixtures 01-14."""
    print('\n[FREE] Regenerating pattern-from-draft (fixtures 01-14) via generate_fixtures.py …')
    return _run(
        [VENV_PYTHON, os.path.join(SCRIPTS_DIR, 'generate_fixtures.py')],
        dry_run,
        'generate_fixtures.py',
    )


def step_paid_claude(dry_run: bool, force: bool) -> bool:
    """Regenerate pattern-from-claude.* where data is newer (or --force-paid).

    Synthetic-data fixtures (01-14) are only regenerated when --force-paid is
    active: their data.xlsx timestamp is not a reliable staleness signal because
    generate_fixtures.py always rewrites those files even on content-identical runs.
    """
    print('\n[PAID] Checking claude patterns for staleness …')
    fixtures_to_run = []
    for name in _all_fixtures():
        folder = os.path.join(FIXTURES_DIR, name)
        pat = os.path.join(folder, f'{name}_pattern-from-claude.xlsx')
        synthetic = name in _SYNTHETIC_DATA_FIXTURES
        if force:
            fixtures_to_run.append(name)
            print(f'  {name}: forced regeneration')
        elif not os.path.exists(pat):
            fixtures_to_run.append(name)
            print(f'  {name}: needs regeneration (missing)')
        elif synthetic:
            print(f'  {name}: synthetic data — skip (use --force-paid to refresh)')
        elif _is_stale(folder, pat):
            fixtures_to_run.append(name)
            print(f'  {name}: needs regeneration (data newer)')
        else:
            print(f'  {name}: up to date — skip')
    if not fixtures_to_run:
        print('  All claude patterns are up to date.')
        return True
    return _run(
        [VENV_PYTHON, os.path.join(SCRIPTS_DIR, 'regenerate_drafts.py'),
         '--backend', 'claude', *fixtures_to_run],
        dry_run,
        f'regenerate_drafts.py --backend claude ({len(fixtures_to_run)} fixture(s))',
    )


def step_paid_local(dry_run: bool, force: bool) -> bool:
    """Regenerate pattern-from-local.* for supported fixtures where data is newer.

    Same synthetic-data rule as step_paid_claude: 03/08 are synthetic (skip
    unless --force-paid); 16/21 are real-world (apply staleness check).
    """
    print('\n[PAID] Checking local-model patterns for staleness …')
    fixtures_to_run = []
    for name in _LOCAL_BACKEND_FIXTURES:
        folder = os.path.join(FIXTURES_DIR, name)
        pat = os.path.join(folder, f'{name}_pattern-from-local.xlsx')
        synthetic = name in _SYNTHETIC_DATA_FIXTURES
        if force:
            fixtures_to_run.append(name)
            print(f'  {name}: forced regeneration')
        elif not os.path.exists(pat):
            fixtures_to_run.append(name)
            print(f'  {name}: needs regeneration (missing)')
        elif synthetic:
            print(f'  {name}: synthetic data — skip (use --force-paid to refresh)')
        elif _is_stale(folder, pat):
            fixtures_to_run.append(name)
            print(f'  {name}: needs regeneration (data newer)')
        else:
            print(f'  {name}: up to date — skip')
    if not fixtures_to_run:
        print('  All local patterns are up to date.')
        return True
    return _run(
        [VENV_PYTHON, os.path.join(SCRIPTS_DIR, 'regenerate_drafts.py'),
         '--backend', 'local', *fixtures_to_run],
        dry_run,
        f'regenerate_drafts.py --backend local ({len(fixtures_to_run)} fixture(s))',
    )


def step_snapshots(dry_run: bool) -> bool:
    """Regenerate all snapshots (extraction only, no LLM cost)."""
    print('\n[FREE] Regenerating all snapshots via generate_snapshots.py …')
    return _run(
        [VENV_PYTHON, os.path.join(SCRIPTS_DIR, 'generate_snapshots.py'), '--all'],
        dry_run,
        'generate_snapshots.py --all',
    )


def step_sync_examples(dry_run: bool) -> bool:
    """Sync bundled example files from updated fixture sources."""
    print('\n[FREE] Syncing grepxcel/examples/ from fixture sources …')
    # Map: example_name → source_fixture (from examples_generator.py EXAMPLES list)
    mapping = {
        '01_simple_invoice':   ('01_simple_invoice', None),       # uses manual
        '02_product_catalog':  ('02_product_catalog', None),      # uses manual
        '03_expense_report':   ('05_expense_report', None),       # uses manual
        '04_loan_schedule':    ('11_loan_schedule', 'claude'),     # no manual → use claude
    }
    examples_dir = os.path.join(ROOT, 'grepxcel', 'examples')
    import shutil
    from tests.conftest import find_data_file, find_pattern_xlsx_for_example
    ok = True
    for ex_name, (src_fixture, _backend) in mapping.items():
        src_folder = os.path.join(FIXTURES_DIR, src_fixture)
        # data.xlsx
        src_data = find_data_file(src_folder)
        dst_data = os.path.join(examples_dir, ex_name, 'data.xlsx')
        if not dry_run:
            shutil.copy2(src_data, dst_data)
        print(f'  {ex_name}/data.xlsx  ← {src_fixture}')
    return ok


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--paid', action='store_true',
                        help='Also regenerate paid (LLM) patterns where data is newer')
    parser.add_argument('--force-paid', action='store_true',
                        help='Regenerate all paid patterns unconditionally (implies --paid)')
    parser.add_argument('--skip-free', action='store_true',
                        help='Skip draft pattern + snapshot regeneration (only run --paid tier)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be done without executing')
    args = parser.parse_args()

    if args.force_paid:
        args.paid = True

    print('=== regenerate_all_fixtures.py ===')
    if args.dry_run:
        print('DRY RUN MODE — no files will be changed\n')

    print('\nProtected files (never touched):')
    print('  *_data.xlsx, *_data-cdr.xlsx, *-manual.*, *_extraction_config.json')
    print(f'  *_pattern-from-draft.* for: {", ".join(sorted(_DRAFT_HAND_AUTHORED))}')

    errors = []

    if not args.skip_free:
        if not step_free_draft(args.dry_run):
            errors.append('generate_fixtures.py failed')
    else:
        print('\n[FREE] Skipping draft pattern regeneration (--skip-free)')

    if args.paid:
        if not step_paid_claude(args.dry_run, args.force_paid):
            errors.append('claude regeneration failed')
        if not step_paid_local(args.dry_run, args.force_paid):
            errors.append('local regeneration failed')
    else:
        print('\n[PAID] Skipping LLM pattern regeneration (pass --paid to enable)')

    if not args.skip_free:
        if not step_snapshots(args.dry_run):
            errors.append('generate_snapshots.py failed')
    else:
        print('\n[FREE] Skipping snapshot regeneration (--skip-free)')

    if not args.skip_free:
        # Sync examples data files (free; just file copies)
        try:
            sys.path.insert(0, ROOT)
            from tests.conftest import find_data_file
            import shutil
            mapping = [
                ('01_simple_invoice',  '01_simple_invoice'),
                ('02_product_catalog', '02_product_catalog'),
                ('03_expense_report',  '05_expense_report'),
                ('04_loan_schedule',   '11_loan_schedule'),
            ]
            examples_dir = os.path.join(ROOT, 'grepxcel', 'examples')
            print('\n[FREE] Syncing grepxcel/examples/ data files …')
            for ex_name, src_fixture in mapping:
                src_folder = os.path.join(FIXTURES_DIR, src_fixture)
                src_data = find_data_file(src_folder)
                dst_data = os.path.join(examples_dir, ex_name, 'data.xlsx')
                if not args.dry_run:
                    shutil.copy2(src_data, dst_data)
                print(f'  {ex_name}/data.xlsx  ← {src_fixture}')
        except Exception as exc:
            print(f'  WARNING: examples sync failed: {exc}', file=sys.stderr)

    print('\n' + '='*40)
    if errors:
        print(f'DONE with {len(errors)} error(s):')
        for e in errors:
            print(f'  ✗ {e}')
        sys.exit(1)
    else:
        print('DONE — all steps completed successfully.')
        if not args.paid:
            print('\nNote: LLM patterns (claude, local) were NOT regenerated.')
            print('Run with --paid to regenerate them (only when data.xlsx files change).')


if __name__ == '__main__':
    main()
