"""Tests for the `docs` reference generator (grepxcel.docs_generator)."""
import zipfile

import openpyxl

from grepxcel.docs_generator import DocsGenerator


def test_output_is_byte_deterministic(tmp_path):
    """Two generations must be byte-identical so the docs-reference CI check
    (a byte diff) is meaningful — openpyxl otherwise stamps now()."""
    a = tmp_path / 'a'
    b = tmp_path / 'b'
    DocsGenerator().write(str(a))
    DocsGenerator().write(str(b))
    assert (a / 'pattern-reference.xlsx').read_bytes() == (b / 'pattern-reference.xlsx').read_bytes()
    assert (a / 'grepxcel-guide.docx').read_bytes() == (b / 'grepxcel-guide.docx').read_bytes()


def test_output_is_a_valid_workbook(tmp_path):
    DocsGenerator().write(str(tmp_path))
    wb = openpyxl.load_workbook(tmp_path / 'pattern-reference.xlsx')
    assert wb.sheetnames[0] == 'guide'
    assert 'pattern-reference' in wb.sheetnames


def test_source_date_epoch_is_honored(tmp_path, monkeypatch):
    monkeypatch.setenv('SOURCE_DATE_EPOCH', '1577836800')  # 2020-01-01T00:00:00Z
    DocsGenerator().write(str(tmp_path))
    wb = openpyxl.load_workbook(tmp_path / 'pattern-reference.xlsx')
    assert wb.properties.created.year == 2020


def test_lists_the_new_field_types(tmp_path):
    DocsGenerator().write(str(tmp_path))
    wb = openpyxl.load_workbook(tmp_path / 'pattern-reference.xlsx')
    text = ' '.join(
        str(c.value)
        for ws in wb.worksheets
        for row in ws.iter_rows()
        for c in row
        if c.value
    )
    for t in ('text', 'number', 'boolean'):
        assert t in text


def test_docx_is_generated(tmp_path):
    DocsGenerator().write(str(tmp_path))
    docx = tmp_path / 'grepxcel-guide.docx'
    assert docx.exists()
    with zipfile.ZipFile(docx) as zf:
        names = zf.namelist()
    assert 'word/document.xml' in names
    assert 'word/styles.xml' in names
    assert '[Content_Types].xml' in names


def test_write_returns_both_paths(tmp_path):
    paths = DocsGenerator().write(str(tmp_path))
    assert len(paths) == 2
    assert any('pattern-reference.xlsx' in p for p in paths)
    assert any('grepxcel-guide.docx' in p for p in paths)


# ── Reproducibility ─────────────────────────────────────────────────────────
# ci.yml's docs-reference job regenerates both files and byte-compares them
# against the committed copies. That can only work if generation is
# deterministic. _pin_core_timestamps already normalised the ZIP entry times,
# but two CONTENT fields still changed on every run and silently defeated it:
# a wall-clock now(), and abspath(sys.argv[0]) — which also wrote a local home
# directory into a document that ships to users.

import os as _os_repro
import zipfile as _zipfile_repro
from pathlib import Path as _Path_repro


def _generated_meta_lines(xlsx_path):
    import openpyxl as _o
    wb = _o.load_workbook(xlsx_path)
    return [
        c.value
        for ws in wb.worksheets
        for row in ws.iter_rows()
        for c in row
        if isinstance(c.value, str)
        and (c.value.startswith('Generated:') or c.value.startswith('Executable:'))
    ]


def test_two_runs_produce_byte_identical_files(tmp_path):
    a, b = tmp_path / 'a', tmp_path / 'b'
    DocsGenerator().write(str(a))
    DocsGenerator().write(str(b))
    for name in ('pattern-reference.xlsx', 'grepxcel-guide.docx'):
        assert (a / name).read_bytes() == (b / name).read_bytes(), (
            f'{name} differs between two runs — the docs-reference CI job '
            f'byte-compares a fresh build against the committed copy, so any '
            f'non-determinism makes that check impossible to satisfy'
        )


def test_no_absolute_path_is_embedded(tmp_path):
    """The executable line used to carry abspath(sys.argv[0]), putting a local
    home directory into a user-facing document."""
    DocsGenerator().write(str(tmp_path))
    lines = _generated_meta_lines(tmp_path / 'pattern-reference.xlsx')
    assert lines, 'the GENERATED BY block vanished'
    for line in lines:
        assert not _os_repro.sep + 'home' + _os_repro.sep in line, line
        assert not line.strip().endswith(('/grepxcel', '\\grepxcel.exe')) or \
            'Executable: grepxcel' in line, line


def test_source_date_epoch_controls_the_generated_date(tmp_path, monkeypatch):
    """Release builds can stamp a real date without breaking reproducibility."""
    monkeypatch.setenv('SOURCE_DATE_EPOCH', '1700000000')   # 2023-11-14 UTC
    DocsGenerator().write(str(tmp_path))
    lines = _generated_meta_lines(tmp_path / 'pattern-reference.xlsx')
    assert any('2023-11-14' in l for l in lines), lines


def test_the_committed_docs_are_current(tmp_path):
    """Mirrors the CI job locally, so drift is caught before the push."""
    repo_docs = _Path_repro(__file__).resolve().parents[2] / 'docs'
    DocsGenerator().write(str(tmp_path))
    for name in ('pattern-reference.xlsx', 'grepxcel-guide.docx'):
        assert (repo_docs / name).read_bytes() == (tmp_path / name).read_bytes(), (
            f"docs/{name} is out of date — run 'grepxcel docs -o docs/ --force' "
            f"and commit the result"
        )
